services:
  security-brocker:
    image: rabbitmq:4.0.7-management
    hostname: security-brocker
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 3s
      retries: 10


  security-monitor:
    image: ${DOCKER_REGISTRY-}cybergreenhousesecuritymonitor
    build:
      context: ..
      dockerfile: src/Core/CyberGreenhouse.SecurityMonitor/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
    depends_on:
        security-brocker:
            condition: service_healthy


  main-control:
    image: ${DOCKER_REGISTRY-}cybergreenhousemaincontrol
    build:
      context: ..
      dockerfile: src/Modules/CyberGreenhouse.MainControl/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
    ports:
      - 8080:8080
    depends_on:
        security-brocker:
            condition: service_healthy


  climate-control:
    image: ${DOCKER_REGISTRY-}cybergreenhouseclimatecontrol
    build:
      context: ..
      dockerfile: src/Modules/CyberGreenhouse.ClimateControl/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
    depends_on:
        security-brocker:
            condition: service_healthy

      
  harvesting:
    image: ${DOCKER_REGISTRY-}cybergreenhouseharvesting
    build:
      context: ..
      dockerfile: src/Modules/CyberGreenhouse.Harvesting/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
    ports:
      - 8081:8080
    depends_on:
        security-brocker:
            condition: service_healthy


  irrigation:
    image: ${DOCKER_REGISTRY-}cybergreenhouseirrigation
    build:
      context: ..
      dockerfile: src/Modules/CyberGreenhouse.Irrigation/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
    depends_on:
        security-brocker:
            condition: service_healthy


  lighting:
    image: ${DOCKER_REGISTRY-}cybergreenhouselighting
    build:
      context: ..
      dockerfile: src/Modules/CyberGreenhouse.Lighting/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
    depends_on:
        security-brocker:
            condition: service_healthy


  planting:
    image: ${DOCKER_REGISTRY-}cybergreenhouseplanting
    build:
      context: ..
      dockerfile: src/Modules/CyberGreenhouse.Planting/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
    ports:
      - 8082:8080
    depends_on:
        security-brocker:
            condition: service_healthy


  ripeness-monitor:
    image: ${DOCKER_REGISTRY-}cybergreenhouseripenessmonitor
    build:
      context: ..
      dockerfile: src/Modules/CyberGreenhouse.RipenessMonitor/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
    depends_on:
        security-brocker:
            condition: service_healthy


  plantdata-signature-checker:
    image: ${DOCKER_REGISTRY-}cybergreenhouseplantdatasignaturechecker
    build:
      context: ..
      dockerfile: src/Modules/CyberGreenhouse.PlantDataSignatureChecker/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
        ConnectionStrings__Database: external-database
    depends_on:
        security-brocker:
            condition: service_healthy


  external-database:
    image: ${DOCKER_REGISTRY-}cybergreenhouseexternaldatabase
    build:
      context: ..
      dockerfile: src/External/CyberGreenhouse.External.Database/Dockerfile

