services:
  security-brocker:
    image: rabbitmq:4.0.7-management
    hostname: security-brocker
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 3s
      retries: 10


  security-monitor:
    image: ${DOCKER_REGISTRY-}cybergreenhousesecuritymonitor
    build:
      context: ..
      dockerfile: src/Core/CyberGreenhouse.SecurityMonitor/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
        DOTNET_ENVIRONMENT: Development
    depends_on:
        security-brocker:
            condition: service_healthy


  main-control:
    image: ${DOCKER_REGISTRY-}cybergreenhousemaincontrol
    build:
      context: ..
      dockerfile: src/Modules/CyberGreenhouse.MainControl/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
        DOTNET_ENVIRONMENT: Development
        HasExploit: true
    ports:
      - 8080:8080
    depends_on:
        security-brocker:
            condition: service_healthy


  growing-cycle-control-module:
    image: ${DOCKER_REGISTRY-}cybergreenhousegrowingcyclecontrolmodule
    build:
      context: ..
      dockerfile: src/Modules/CyberGreenhouse.GrowingCycleControlModule/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
        DOTNET_ENVIRONMENT: Development
    depends_on:
        security-brocker:
            condition: service_healthy


  plantdata-signature-checker:
    image: ${DOCKER_REGISTRY-}cybergreenhouseplantdatasignaturechecker
    build:
      context: ..
      dockerfile: src/Modules/CyberGreenhouse.PlantDataSignatureChecker/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
        DOTNET_ENVIRONMENT: Development
        ConnectionStrings__Database: http://external-database:8080
    depends_on:
        security-brocker:
            condition: service_healthy


  external-database:
    image: ${DOCKER_REGISTRY-}cybergreenhouseexternaldatabase
    build:
      context: ..
      dockerfile: src/External/CyberGreenhouse.External.Database/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: Development
    ports:
      - 8090:8080


  lighting-control-module:
    image: ${DOCKER_REGISTRY-}cybergreenhouselightinglightingcontrolmodule
    build:
      context: ..
      dockerfile: src/Modules/Lighting/CyberGreenhouse.Lighting.LightingControlModule/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
        DOTNET_ENVIRONMENT: Development
    depends_on:
        security-brocker:
            condition: service_healthy


  light-sensor-filter-module:
    image: ${DOCKER_REGISTRY-}cybergreenhouselightinglightsensorfiltermodule
    build:
      context: ..
      dockerfile: src/Modules/Lighting/CyberGreenhouse.Lighting.LightSensorFilterModule/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
        DOTNET_ENVIRONMENT: Development
    depends_on:
        security-brocker:
            condition: service_healthy
  

  climate-control-module:
    image: ${DOCKER_REGISTRY-}cybergreenhouseclimatecontrolclimatecontrolmodule
    build:
      context: ..
      dockerfile: src/Modules/ClimateControl/CyberGreenhouse.ClimateControl.ClimateControlModule/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
        DOTNET_ENVIRONMENT: Development
    depends_on:
        security-brocker:
            condition: service_healthy


  air-termosensor-filter-module:
    image: ${DOCKER_REGISTRY-}cybergreenhouseclimatecontrolairtermosensorfiltermodule
    build:
      context: ..
      dockerfile: src/Modules/ClimateControl/CyberGreenhouse.ClimateControl.AirTermoSensorFilterModule/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
        DOTNET_ENVIRONMENT: Development
    depends_on:
        security-brocker:
            condition: service_healthy


  water-termosensor-filter-module:
    image: ${DOCKER_REGISTRY-}cybergreenhouseclimatecontrolwatertermosensorfiltermodule
    build:
      context: ..
      dockerfile: src/Modules/ClimateControl/CyberGreenhouse.ClimateControl.WaterTermoSensorFilterModule/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
        DOTNET_ENVIRONMENT: Development
    depends_on:
        security-brocker:
            condition: service_healthy


  air-humiditysensor-filter-module:
    image: ${DOCKER_REGISTRY-}cybergreenhouseclimatecontrolairhumiditysensorfiltermodule
    build:
      context: ..
      dockerfile: src/Modules/ClimateControl/CyberGreenhouse.ClimateControl.AirHumiditySensorFilterModule/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
        DOTNET_ENVIRONMENT: Development
    depends_on:
        security-brocker:
            condition: service_healthy


  irrigation-control-module:
    image: ${DOCKER_REGISTRY-}cybergreenhouseirrigationirrigationcontrolmodule
    build:
      context: ..
      dockerfile: src/Modules/Irrigation/CyberGreenhouse.Irrigation.IrrigationControlModule/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
        DOTNET_ENVIRONMENT: Development
    depends_on:
         security-brocker:
             condition: service_healthy


  nutrient-composition-control-module:
    image: ${DOCKER_REGISTRY-}cybergreenhouseirrigationnutrientcompositioncontrolmodule
    build:
      context: ..
      dockerfile: src/Modules/Irrigation/CyberGreenhouse.Irrigation.NutrientCompositionControlModule/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
        DOTNET_ENVIRONMENT: Development
    depends_on:
         security-brocker:
             condition: service_healthy


  soil-humiditysensor-filter-module:
    image: ${DOCKER_REGISTRY-}cybergreenhouseirrigationsoilhumiditysensorfiltermodule
    build:
      context: ..
      dockerfile: src/Modules/Irrigation/CyberGreenhouse.Irrigation.SoilHumiditySensorFilterModule/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
        DOTNET_ENVIRONMENT: Development
    depends_on:
         security-brocker:
             condition: service_healthy


  maturity-monitoring-control-module:
    image: ${DOCKER_REGISTRY-}cybergreenhousematuritymonitoringmaturitymonitoringcontrolmodule
    build:
      context: ..
      dockerfile: src/Modules/MaturityMonitoring/CyberGreenhouse.MaturityMonitoring.MaturityMonitoringControlModule/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
        DOTNET_ENVIRONMENT: Development
    depends_on:
         security-brocker:
             condition: service_healthy

  time-control-module:
    image: ${DOCKER_REGISTRY-}cybergreenhousematuritymonitoringtimecontrolmodule
    build:
      context: ..
      dockerfile: src/Modules/MaturityMonitoring/CyberGreenhouse.MaturityMonitoring.TimeControlModule/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
        DOTNET_ENVIRONMENT: Development
    depends_on:
         security-brocker:
             condition: service_healthy


  visual-inspection-module:
    image: ${DOCKER_REGISTRY-}cybergreenhousematuritymonitoringvisualinspectionmodule
    build:
      context: ..
      dockerfile: src/Modules/MaturityMonitoring/CyberGreenhouse.MaturityMonitoring.VisualInspectionModule/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
        DOTNET_ENVIRONMENT: Development
    depends_on:
         security-brocker:
             condition: service_healthy


  harvesting-module:
    image: ${DOCKER_REGISTRY-}cybergreenhouseharvestingmodule
    build:
      context: ..
      dockerfile: src/Modules/CyberGreenhouse.HarvestingModule/Dockerfile
    ports:
      - 8082:8080
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
        DOTNET_ENVIRONMENT: Development
        HarvestingSettings__IsAutoComplete: true
    depends_on:
         security-brocker:
             condition: service_healthy


  planting-module:
    image: ${DOCKER_REGISTRY-}cybergreenhouseplantingmodule
    build:
      context: ..
      dockerfile: src/Modules/CyberGreenhouse.PlantingModule/Dockerfile
    ports:
      - 8081:8080
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
        DOTNET_ENVIRONMENT: Development
        PlantingSettings__IsAutoComplete: true
    depends_on:
         security-brocker:
             condition: service_healthy


  emergency-stop-module:
    image: ${DOCKER_REGISTRY-}cybergreenhouseemergencystopmodule
    build:
      context: ..
      dockerfile: src/Modules/CyberGreenhouse.EmergencyStopModule/Dockerfile
    environment:
        MessageBusConnection__RabbitMQ__Host: security-brocker
        DOTNET_ENVIRONMENT: Development
    depends_on:
         security-brocker:
             condition: service_healthy

