services:
  security-monitor:
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro


  # main-control:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080


  # climate-control:
  #   environment:
  #     - DOTNET_ENVIRONMENT=Development
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro


  # harvesting:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080


  # irrigation:
  #   environment:
  #     - DOTNET_ENVIRONMENT=Development
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro


  # lighting:
  #   environment:
  #     - DOTNET_ENVIRONMENT=Development
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro


  # planting:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080


  # ripeness-monitor:
  #   environment:
  #     - DOTNET_ENVIRONMENT=Development
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  # plantdata-signature-checker:
  #   environment:
  #     - DOTNET_ENVIRONMENT=Development
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  # external-database:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080


  # lighting-control-module:
  #   environment:
  #     - DOTNET_ENVIRONMENT=Development
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  # light-sensor-filter-module:
  #   environment:
  #     - DOTNET_ENVIRONMENT=Development
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  # climate-control-module:
  #   environment:
  #     - DOTNET_ENVIRONMENT=Development
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  # air-termosensor-filter-module:
  #   environment:
  #     - DOTNET_ENVIRONMENT=Development
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  # water-termosensor-filter-module:
  #   environment:
  #     - DOTNET_ENVIRONMENT=Development
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  # air-humiditysensor-filter-module:
  #   environment:
  #     - DOTNET_ENVIRONMENT=Development
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  irrigation-control-module:
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  nutrient-composition-control-module:
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  soil-humiditysensor-filter-module:
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
